# Transformación, filtración y ordenamiento de datos

### 1. Revisión de tipos de datos de los dos dataFrames

#### DF Mintic

In [322]:
df_mintic_v2.dtypes

id                  object
FECHA_CORTE         object
DEPARTAME_NOMBRE    object
MUNICIPIO_NOMBRE    object
ESTADO_FORMACION    object
ESTADOS             object
ESTRATO_SOCIAL      object
EDAD                object
GENERO              object
RUTA                object
GRADO               object
dtype: object

In [323]:
df_mintic_v2.head(3)

id FECHA_CORTE DEPARTAME_NOMBRE  \
0  00000000-0000-0000-C200-BA92F054D3BD  2021-10-01          QUINDIO   
1  00000000-0000-0000-99AA-2E3888BFFB24  2021-10-01          QUINDIO   
2  00000000-0000-0000-D72E-7CF7C7526A22  2021-10-01          QUINDIO   

  MUNICIPIO_NOMBRE ESTADO_FORMACION     ESTADOS ESTRATO_SOCIAL EDAD  \
0          ARMENIA        ASPIRANTE  ASPIRANTES              3   29   
1          ARMENIA        ASPIRANTE  ASPIRANTES              3   29   
2          ARMENIA        ASPIRANTE  ASPIRANTES              3   29   

      GENERO    RUTA GRADO  
0  MASCULINO  RUTA 2    -1  
1  MASCULINO  RUTA 2    -1  
2  MASCULINO  RUTA 2    -1

Para el DF de Mintic se modificarán los tipos de datos:
* Estrato_social: moddificación a int
* Edad: modificación a int
* Grado: modificación a int

In [324]:
diccionario_de_conversion_mintic = {
    "ESTRATO_SOCIAL":"int64",
    "EDAD":"int64",
    "GRADO":"int64"
}

In [325]:
df_mintic_v3 = df_mintic_v2
try:
    df_mintic_v3 = df_mintic_v2.astype(diccionario_de_conversion_mintic)
except ValueError as e:
    print(type(e))
    
df_mintic_v3.dtypes

<class 'ValueError'>


id                  object
FECHA_CORTE         object
DEPARTAME_NOMBRE    object
MUNICIPIO_NOMBRE    object
ESTADO_FORMACION    object
ESTADOS             object
ESTRATO_SOCIAL      object
EDAD                object
GENERO              object
RUTA                object
GRADO               object
dtype: object

In [326]:
df_mintic_v3["ESTRATO_SOCIAL"].unique()

array(['3', '1', '2', '4', 'a', '5', '6'], dtype=object)

Me genera error en el estrato social al tratar de convertir a entero, ya que tiene un valor "a".
Se procederá a modificar todos los valores a de esta columna al valor 0, el cuan indicará que no tiene estrato social asignado

In [327]:
# Se aplica el cambio en la versión 2
df_mintic_v2.loc[df_mintic_v2.ESTRATO_SOCIAL=="a",'ESTRATO_SOCIAL'] = 0
df_mintic_v2["ESTRATO_SOCIAL"].unique()

array(['3', '1', '2', '4', 0, '5', '6'], dtype=object)

In [328]:
df_mintic_v3 = df_mintic_v2
try:
    df_mintic_v3 = df_mintic_v2.astype(diccionario_de_conversion_mintic)
except ValueError as e:
    print(type(e))
    
df_mintic_v3.dtypes

id                  object
FECHA_CORTE         object
DEPARTAME_NOMBRE    object
MUNICIPIO_NOMBRE    object
ESTADO_FORMACION    object
ESTADOS             object
ESTRATO_SOCIAL       int64
EDAD                 int64
GENERO              object
RUTA                object
GRADO                int64
dtype: object

In [329]:
df_mintic_v3.head(3)

id FECHA_CORTE DEPARTAME_NOMBRE  \
0  00000000-0000-0000-C200-BA92F054D3BD  2021-10-01          QUINDIO   
1  00000000-0000-0000-99AA-2E3888BFFB24  2021-10-01          QUINDIO   
2  00000000-0000-0000-D72E-7CF7C7526A22  2021-10-01          QUINDIO   

  MUNICIPIO_NOMBRE ESTADO_FORMACION     ESTADOS  ESTRATO_SOCIAL  EDAD  \
0          ARMENIA        ASPIRANTE  ASPIRANTES               3    29   
1          ARMENIA        ASPIRANTE  ASPIRANTES               3    29   
2          ARMENIA        ASPIRANTE  ASPIRANTES               3    29   

      GENERO    RUTA  GRADO  
0  MASCULINO  RUTA 2     -1  
1  MASCULINO  RUTA 2     -1  
2  MASCULINO  RUTA 2     -1

#### DF Saber 11

In [256]:
df_saber_union_v1.dtypes

id                               object
ESTU_NACIONALIDAD                object
ESTU_GENERO                      object
ESTU_FECHANACIMIENTO             object
ESTU_CONSECUTIVO                 object
ESTU_PAIS_RESIDE                 object
ESTU_DEPTO_RESIDE                object
ESTU_COD_RESIDE_DEPTO            object
ESTU_MCPIO_RESIDE                object
ESTU_COD_RESIDE_MCPIO            object
FAMI_ESTRATOVIVIENDA             object
FAMI_TIENEINTERNET               object
FAMI_TIENECOMPUTADOR             object
FAMI_SITUACIONECONOMICA          object
ESTU_DEDICACIONINTERNET          object
PUNT_LECTURA_CRITICA             object
PERCENTIL_LECTURA_CRITICA        object
DESEMP_LECTURA_CRITICA           object
PUNT_MATEMATICAS                 object
PERCENTIL_MATEMATICAS            object
DESEMP_MATEMATICAS               object
PUNT_C_NATURALES                 object
PERCENTIL_C_NATURALES            object
DESEMP_C_NATURALES               object
PUNT_SOCIALES_CIUDADANAS         object


In [257]:
df_saber_union_v1.head(3)

id ESTU_NACIONALIDAD ESTU_GENERO  \
0  00000000-0000-0000-B30A-5F2FE234EE93          COLOMBIA           F   
1  00000000-0000-0000-F3E5-3E18272D8C28          COLOMBIA           F   
2  00000000-0000-0000-2E67-572B8AFB010B          COLOMBIA           F   

  ESTU_FECHANACIMIENTO  ESTU_CONSECUTIVO ESTU_PAIS_RESIDE ESTU_DEPTO_RESIDE  \
0  1985-01-01T00:00:00  SB11202010045555         COLOMBIA             CESAR   
1  1995-01-01T00:00:00  SB11202010045719         COLOMBIA            NARIÑO   
2  1997-01-01T00:00:00  SB11202010070662         COLOMBIA             CAUCA   

  ESTU_COD_RESIDE_DEPTO ESTU_MCPIO_RESIDE ESTU_COD_RESIDE_MCPIO  ...  \
0                    20         SAN DIEGO                 20750  ...   
1                    52           IPIALES                 52356  ...   
2                    19            TOTORÓ                 19824  ...   

  PERCENTIL_C_NATURALES DESEMP_C_NATURALES PUNT_SOCIALES_CIUDADANAS  \
0                     6                  1                       24   
1                    10                  1                       44   
2                     4                  1                       24   

  PERCENTIL_SOCIALES_CIUDADANAS DESEMP_SOCIALES_CIUDADANAS PUNT_INGLES  \
0                             1                          1          36   
1                            23                          2          30   
2                             1                          1          30   

  PERCENTIL_INGLES DESEMP_INGLES PUNT_GLOBAL PERCENTIL_GLOBAL  
0                7            A-         164                2  
1                3            A-         202               10  
2                3            A-         162                2  

[3 rows x 32 columns]

### Se revisan las columnas de Saber 11 según conveniencia y compativilidad con Mintic

La columna "FAMI_ESTRATOVIVIENDA" se transforma a numerica según el texto, para tener relación con la tabla Mintic: El estrato 'None' y 'Sin Estrato', serán transformados en 0

In [258]:
df_saber_union_v1["FAMI_ESTRATOVIVIENDA"].unique()

array(['Estrato 1', None, 'Estrato 6', 'Estrato 5', 'Estrato 2',
       'Estrato 4', 'Estrato 3', 'Sin Estrato'], dtype=object)

In [330]:
#Revisando data de Mintic
df_mintic_v3["ESTRATO_SOCIAL"].unique()

array([3, 1, 2, 4, 0, 5, 6], dtype=int64)

In [260]:
conver_estrato = {
    'Estrato 1': 1,
    'Estrato 2': 2,
    'Estrato 3': 3,
    'Estrato 4': 4,
    'Estrato 5': 5,
    'Estrato 6': 6,
    'Sin Estrato': 0,
    None: 0,
}

In [261]:
df_saber_union_v1["FAMI_ESTRATOVIVIENDA"] = df_saber_union_v1["FAMI_ESTRATOVIVIENDA"].map(conver_estrato)
df_saber_union_v1["FAMI_ESTRATOVIVIENDA"].unique()

array([1, 0, 6, 5, 2, 4, 3], dtype=int64)

Tansformamos la fecha de nacimiento 'ESTU_FECHANACIMIENTO' a la edad debido a que la data de Mintic se encuentra como edad y lo dejaremos como entero

In [262]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
import numpy as np

In [263]:
type(datetime.fromisoformat(df_saber_union_v1["ESTU_FECHANACIMIENTO"][0]))

datetime.datetime

In [264]:
fecha_2020 = datetime.fromisoformat('2020-01-01') # tipo datetime.datetime

In [265]:
# Serie Datetime
ser_nac = pd.Series( datetime.fromisoformat(i) for i in df_saber_union_v1["ESTU_FECHANACIMIENTO"] )
ser_nac.head(2)

0    1985-01-01 00:00:00
1    1995-01-01 00:00:00
dtype: object

Restar fecha 2020 a la fecha de nacimiento para conocer la edad

In [266]:
edades = pd.Series( relativedelta(fecha_2020, ser_nac[m]).years for m in range( len(ser_nac) ) )
edades

0         35
1         25
2         23
3         19
4         18
          ..
520302    16
520303    23
520304    14
520305    17
520306    17
Length: 520307, dtype: int64

In [267]:
df_saber_union_v1["ESTU_FECHANACIMIENTO"] = edades
df_saber_union_v1["ESTU_FECHANACIMIENTO"].head(3)

0    35
1    25
2    23
Name: ESTU_FECHANACIMIENTO, dtype: int64

### Se convertiran todas las columnas que contienen 'Si' y 'No' del dataframe Saber11

* FAMI_TIENEINTERNET
* FAMI_TIENECOMPUTADOR

### Se convertiran todas las columnas numericas a enteros en datafreme Seber 11
* PUNT_LECTURA_CRITICA
* PERCENTIL_LECTURA_CRITICA        
* DESEMP_LECTURA_CRITICA           
* PUNT_MATEMATICAS                 
* PERCENTIL_MATEMATICAS            
* DESEMP_MATEMATICAS               
* PUNT_C_NATURALES                 
* PERCENTIL_C_NATURALES            
* DESEMP_C_NATURALES               
* PUNT_SOCIALES_CIUDADANAS         
* PERCENTIL_SOCIALES_CIUDADANAS    
* DESEMP_SOCIALES_CIUDADANAS       
* PUNT_INGLES                      
* PERCENTIL_INGLES                 
* PUNT_GLOBAL                      
* PERCENTIL_GLOBAL                 

In [268]:
conver_sn = {'No': 0, 'Si': 1, None: None}
conver_sn

{'No': 0, 'Si': 1, None: None}

In [269]:
df_saber_union_v1["FAMI_TIENEINTERNET"] = df_saber_union_v1["FAMI_TIENEINTERNET"].map(conver_sn)
df_saber_union_v1["FAMI_TIENEINTERNET"].unique()

array([ 0., nan,  1.])

In [270]:
df_saber_union_v1["FAMI_TIENEINTERNET"] = df_saber_union_v1["FAMI_TIENEINTERNET"].astype('Int64')
df_saber_union_v1["FAMI_TIENEINTERNET"].unique()

<IntegerArray>
[0, <NA>, 1]
Length: 3, dtype: Int64

In [271]:
df_saber_union_v1["FAMI_TIENECOMPUTADOR"] = df_saber_union_v1["FAMI_TIENECOMPUTADOR"].map(conver_sn)
df_saber_union_v1["FAMI_TIENECOMPUTADOR"].unique()

array([ 0., nan,  1.])

In [272]:
df_saber_union_v1["FAMI_TIENECOMPUTADOR"] = df_saber_union_v1["FAMI_TIENECOMPUTADOR"].astype('Int64')
df_saber_union_v1["FAMI_TIENECOMPUTADOR"].unique()

<IntegerArray>
[0, <NA>, 1]
Length: 3, dtype: Int64

#### Convertir a enteros las calificaciones y puntajes

In [273]:
df_saber_union_v1['PUNT_LECTURA_CRITICA'] = df_saber_union_v1['PUNT_LECTURA_CRITICA'].astype(int)
df_saber_union_v1['PERCENTIL_LECTURA_CRITICA'] = df_saber_union_v1['PERCENTIL_LECTURA_CRITICA'].astype(int)
df_saber_union_v1['DESEMP_LECTURA_CRITICA'] = df_saber_union_v1['DESEMP_LECTURA_CRITICA'].astype(int)
df_saber_union_v1['PUNT_MATEMATICAS'] = df_saber_union_v1['PUNT_MATEMATICAS'].astype(int)
df_saber_union_v1['PERCENTIL_MATEMATICAS'] = df_saber_union_v1['PERCENTIL_MATEMATICAS'].astype(int)
df_saber_union_v1['DESEMP_MATEMATICAS'] = df_saber_union_v1['DESEMP_MATEMATICAS'].astype(int)
df_saber_union_v1['PUNT_C_NATURALES'] = df_saber_union_v1['PUNT_C_NATURALES'].astype(int)
df_saber_union_v1['PERCENTIL_C_NATURALES'] = df_saber_union_v1['PERCENTIL_C_NATURALES'].astype(int)
df_saber_union_v1['DESEMP_C_NATURALES'] = df_saber_union_v1['DESEMP_C_NATURALES'].astype(int)
df_saber_union_v1['PUNT_SOCIALES_CIUDADANAS'] = df_saber_union_v1['PUNT_SOCIALES_CIUDADANAS'].astype(int)
df_saber_union_v1['PERCENTIL_SOCIALES_CIUDADANAS'] = df_saber_union_v1['PERCENTIL_SOCIALES_CIUDADANAS'].astype(int)
df_saber_union_v1['DESEMP_SOCIALES_CIUDADANAS'] = df_saber_union_v1['DESEMP_SOCIALES_CIUDADANAS'].astype(int)
df_saber_union_v1['PERCENTIL_INGLES'] = df_saber_union_v1['PERCENTIL_INGLES'].astype(int)
df_saber_union_v1['PUNT_GLOBAL'] = df_saber_union_v1['PUNT_GLOBAL'].astype(int)

In [274]:
df_saber_union_v1.dtypes

id                               object
ESTU_NACIONALIDAD                object
ESTU_GENERO                      object
ESTU_FECHANACIMIENTO              int64
ESTU_CONSECUTIVO                 object
ESTU_PAIS_RESIDE                 object
ESTU_DEPTO_RESIDE                object
ESTU_COD_RESIDE_DEPTO            object
ESTU_MCPIO_RESIDE                object
ESTU_COD_RESIDE_MCPIO            object
FAMI_ESTRATOVIVIENDA              int64
FAMI_TIENEINTERNET                Int64
FAMI_TIENECOMPUTADOR              Int64
FAMI_SITUACIONECONOMICA          object
ESTU_DEDICACIONINTERNET          object
PUNT_LECTURA_CRITICA              int32
PERCENTIL_LECTURA_CRITICA         int32
DESEMP_LECTURA_CRITICA            int32
PUNT_MATEMATICAS                  int32
PERCENTIL_MATEMATICAS             int32
DESEMP_MATEMATICAS                int32
PUNT_C_NATURALES                  int32
PERCENTIL_C_NATURALES             int32
DESEMP_C_NATURALES                int32
PUNT_SOCIALES_CIUDADANAS          int32


In [275]:
lista_ing = [int(i) if type(i) == str else np.nan for i in df_saber_union_v1["PUNT_INGLES"]]
ser_int_ing = pd.Series(lista_ing).astype('Int64')
#df_saber_union_v1["PUNT_INGLES"] df_saber_union_v1["PUNT_INGLES"].head()
ser_int_ing.head(3)

0    36
1    30
2    30
dtype: Int64

In [276]:
df_saber_union_v1["PUNT_INGLES"] = ser_int_ing
df_saber_union_v1["PUNT_INGLES"].head()

0    36
1    30
2    30
3    37
4    80
Name: PUNT_INGLES, dtype: Int64

In [277]:
lista_per_global = [int(i) if type(i) == str else np.nan for i in df_saber_union_v1["PERCENTIL_GLOBAL"]]
ser_int_glob = pd.Series(lista_per_global).astype('Int64')
ser_int_glob.head(3)

0     2
1    10
2     2
dtype: Int64

In [278]:
df_saber_union_v1["PERCENTIL_GLOBAL"] = ser_int_glob
df_saber_union_v1["PERCENTIL_GLOBAL"].head()

0     2
1    10
2     2
3     6
4    39
Name: PERCENTIL_GLOBAL, dtype: Int64

In [279]:
df_saber_union_v1.dtypes

id                               object
ESTU_NACIONALIDAD                object
ESTU_GENERO                      object
ESTU_FECHANACIMIENTO              int64
ESTU_CONSECUTIVO                 object
ESTU_PAIS_RESIDE                 object
ESTU_DEPTO_RESIDE                object
ESTU_COD_RESIDE_DEPTO            object
ESTU_MCPIO_RESIDE                object
ESTU_COD_RESIDE_MCPIO            object
FAMI_ESTRATOVIVIENDA              int64
FAMI_TIENEINTERNET                Int64
FAMI_TIENECOMPUTADOR              Int64
FAMI_SITUACIONECONOMICA          object
ESTU_DEDICACIONINTERNET          object
PUNT_LECTURA_CRITICA              int32
PERCENTIL_LECTURA_CRITICA         int32
DESEMP_LECTURA_CRITICA            int32
PUNT_MATEMATICAS                  int32
PERCENTIL_MATEMATICAS             int32
DESEMP_MATEMATICAS                int32
PUNT_C_NATURALES                  int32
PERCENTIL_C_NATURALES             int32
DESEMP_C_NATURALES                int32
PUNT_SOCIALES_CIUDADANAS          int32


In [280]:
df_saber_union_v1['ESTU_FECHANACIMIENTO'].unique()

array([  35,   25,   23,   19,   18,   37,   30,   20,   17, 2018,   22,
         21,   39,   26,   24,   36,   43,   27,   50,   33,   32,   45,
         42,   31,   28,   34,   48,   29,   57,   51,   47,   40,   38,
         14,   52, 1932,   15,   44,   60,   41,   16,   49,   55,   61,
         53, 2017,   54,   46,   58,   10,   56,    9,  120,   64, 1923,
       1934,    0, 1939, 2016, 1921, 1920, 2008, 2019, 2015,    1, 2014,
          8,    3,   12,   11, 2013, 2010,    6,   13,   66,    7,   68,
         74,   62,   67,   59,   65,  824,   63,    5,   73,    4,   75,
         78,   79,   71,   69,   80,   70,   72], dtype=int64)

Función para convertir edades no lógicas a vacíos

In [286]:
def conv_edad(edad):
    if edad > 99 or edad <= 9:
        return np.nan
    else:
        return edad

In [288]:
lista_edades_nuevas = [conv_edad(i) for i in df_saber_union_v1['ESTU_FECHANACIMIENTO']]

In [289]:
df_saber_union_v1['ESTU_FECHANACIMIENTO'] = lista_edades_nuevas
df_saber_union_v1['ESTU_FECHANACIMIENTO'].head(3)

0    35.0
1    25.0
2    23.0
Name: ESTU_FECHANACIMIENTO, dtype: float64

In [291]:
ser_int_Fnac = pd.Series(df_saber_union_v1['ESTU_FECHANACIMIENTO']).astype('Int64')
ser_int_Fnac

0         35
1         25
2         23
3         19
4         18
          ..
520302    16
520303    23
520304    14
520305    17
520306    17
Name: ESTU_FECHANACIMIENTO, Length: 520307, dtype: Int64

In [296]:
df_saber_union_v1['ESTU_FECHANACIMIENTO'] = ser_int_Fnac
df_saber_union_v1['ESTU_FECHANACIMIENTO'].unique()

<IntegerArray>
[  35,   25,   23,   19,   18,   37,   30,   20,   17, <NA>,   22,   21,   39,
   26,   24,   36,   43,   27,   50,   33,   32,   45,   42,   31,   28,   34,
   48,   29,   57,   51,   47,   40,   38,   14,   52,   15,   44,   60,   41,
   16,   49,   55,   61,   53,   54,   46,   58,   10,   56,   64,   12,   11,
   13,   66,   68,   74,   62,   67,   59,   65,   63,   73,   75,   78,   79,
   71,   69,   80,   70,   72]
Length: 70, dtype: Int64

#### Cambio de nombre de la columna, ya que representa la edad y ya no representa la fecha de nacimiento

In [294]:
df_saber_union_v2 = df_saber_union_v1.rename(columns={'ESTU_FECHANACIMIENTO':'ESTU_EDAD'})
df_saber_union_v2.dtypes

id                               object
ESTU_NACIONALIDAD                object
ESTU_GENERO                      object
ESTU_EDAD                         Int64
ESTU_CONSECUTIVO                 object
ESTU_PAIS_RESIDE                 object
ESTU_DEPTO_RESIDE                object
ESTU_COD_RESIDE_DEPTO            object
ESTU_MCPIO_RESIDE                object
ESTU_COD_RESIDE_MCPIO            object
FAMI_ESTRATOVIVIENDA              int64
FAMI_TIENEINTERNET                Int64
FAMI_TIENECOMPUTADOR              Int64
FAMI_SITUACIONECONOMICA          object
ESTU_DEDICACIONINTERNET          object
PUNT_LECTURA_CRITICA              int32
PERCENTIL_LECTURA_CRITICA         int32
DESEMP_LECTURA_CRITICA            int32
PUNT_MATEMATICAS                  int32
PERCENTIL_MATEMATICAS             int32
DESEMP_MATEMATICAS                int32
PUNT_C_NATURALES                  int32
PERCENTIL_C_NATURALES             int32
DESEMP_C_NATURALES                int32
PUNT_SOCIALES_CIUDADANAS          int32


In [295]:
[df_saber_union_v2[col].unique() for col in df_saber_union_v2.columns]

[array(['00000000-0000-0000-B30A-5F2FE234EE93',
        '00000000-0000-0000-F3E5-3E18272D8C28',
        '00000000-0000-0000-2E67-572B8AFB010B', ...,
        '00000000-0000-0000-2F10-A90012384309',
        '00000000-0000-0000-03B3-B2EA58E0923E',
        '00000000-0000-0000-2054-CB6AE8FC9320'], dtype=object),
 array(['COLOMBIA', 'ESPAÑA', 'ESTADOS UNIDOS', 'HONDURAS',
        'PAÍSES BAJOS - HOLANDA', 'ALEMANIA', 'ARGENTINA', 'BRASIL',
        'CHILE', 'COREA DEL NORTE', 'CUBA', 'ECUADOR', 'EL SALVADOR',
        'FRANCIA', 'GUATEMALA', 'HAITI', 'ITALIA', 'MÉXICO', 'NICARAGUA',
        'PORTUGAL', 'VENEZUELA', 'SUIZA', 'PERÚ', 'COREA DEL SUR',
        'URUGUAY', 'ESTADOS FEDERADOS DE MICRONESIA', 'BOLIVIA', 'PANAMÁ',
        'REPÚBLICA DOMINICANA', 'WALLIS Y FUTUNA', 'CABO VERDE', 'VANUATU',
        'VIETNAM', 'JAPÓN', 'ARABIA SAUDITA', 'RUSIA', 'EGIPTO', 'IRÁN',
        'REINO UNIDO', 'COSTA RICA', 'CHINA', 'LITUANIA', 'CURAZAO',
        'ARUBA', 'PARAGUAY', 'CANADÁ', 'TURQUÍA', 'OMÁN'],

#### De la información resultante y de acuerdo para el análisis se dejaran los resultados solo de Colombia para analisar el programa del gobierno

In [303]:
df_saber_union_v3 = df_saber_union_v2[ df_saber_union_v2['ESTU_NACIONALIDAD'] == 'COLOMBIA']

In [307]:
df_saber_union_v4 = df_saber_union_v3[ df_saber_union_v3['ESTU_EDAD'] != np.nan]
df_saber_union_v4.head(3)

id ESTU_NACIONALIDAD ESTU_GENERO  \
0  00000000-0000-0000-B30A-5F2FE234EE93          COLOMBIA           F   
1  00000000-0000-0000-F3E5-3E18272D8C28          COLOMBIA           F   
2  00000000-0000-0000-2E67-572B8AFB010B          COLOMBIA           F   

   ESTU_EDAD  ESTU_CONSECUTIVO ESTU_PAIS_RESIDE ESTU_DEPTO_RESIDE  \
0         35  SB11202010045555         COLOMBIA             CESAR   
1         25  SB11202010045719         COLOMBIA            NARIÑO   
2         23  SB11202010070662         COLOMBIA             CAUCA   

  ESTU_COD_RESIDE_DEPTO ESTU_MCPIO_RESIDE ESTU_COD_RESIDE_MCPIO  ...  \
0                    20         SAN DIEGO                 20750  ...   
1                    52           IPIALES                 52356  ...   
2                    19            TOTORÓ                 19824  ...   

   PERCENTIL_C_NATURALES  DESEMP_C_NATURALES  PUNT_SOCIALES_CIUDADANAS  \
0                      6                   1                        24   
1                     10                   1                        44   
2                      4                   1                        24   

  PERCENTIL_SOCIALES_CIUDADANAS DESEMP_SOCIALES_CIUDADANAS  PUNT_INGLES  \
0                             1                          1           36   
1                            23                          2           30   
2                             1                          1           30   

   PERCENTIL_INGLES  DESEMP_INGLES  PUNT_GLOBAL  PERCENTIL_GLOBAL  
0                 7             A-          164                 2  
1                 3             A-          202                10  
2                 3             A-          162                 2  

[3 rows x 32 columns]

In [308]:
df_saber_union_v4.shape

(513198, 32)

In [312]:
df_saber_union_v4.to_csv('saber_11_union.csv', index=False)

In [331]:
df_mintic_v3.to_csv('Mintic_datos_limpios.csv', index=False)