## Limpieza de Datos

### 1. Busquda de NaNs
Explora tu dataset con el fin de encontrar los NaNs que contiene. Piensa en la distribución de NaNs por columna y por fila.

In [108]:
import numpy as np

1. Se encuentra que las siguientes columnas y los datos en sus corresponidientes filas, no tienen ningún registro asociado para el DataFrame del Mintic:
* created_meta
* updated_meta 
* META_BENEFICIARIO
* INVERSION 
* META_DINERO

In [111]:
df_mintic.isna().sum()

sid                       0
id                        0
position                  0
created_at                0
created_meta         429699
updated_at                0
updated_meta         429699
meta                      0
FECHA_CORTE               0
DEPARTAME_NOMBRE          0
MUNICIPIO_NOMBRE          0
ESTADO_FORMACION          0
ESTADOS                   0
CONVOCATORIA              0
ESTRATO_SOCIAL            0
EDAD                      0
GENERO                    0
RUTA                      0
GRADO                     0
META_BENEFICIARIO    429699
INVERSION            429699
META_DINERO          429699
FECHA_VIGENCIA            0
dtype: int64

In [171]:
# Guardar el número de registro y cantidad de nans
serie_registros_mintic_nan = df_mintic.isna().sum(axis=1)

# Revisar cuantos registros tienen más de las 5 columnas con Nan
[serie_registros_mintic_nan.index[i] for i in range(len(serie_registros_mintic_nan)) if serie_registros_mintic_nan[i] != 5 ]

[]

2.  Las siguientes columnas contienen todos sus datos con NaNs para el DF Saber 11 periodo 1

In [174]:
# SABER 11 PERIODO 1
columnas_nan_saber_1 = []

# Obtener la serie con el nombre de la columna y cantidad de registros con NaN
res_nans_saber_1 = df_saber_1.isna().sum()

# Buscar y guardar en una lista el nombre de las columnas que tienen todos sus registros con Nan
columnas_nan_saber_1 = [res_nans_saber_1.index[i] for i in range(len(res_nans_saber_1)) if res_nans_saber_1[i] == 15435]
columnas_nan_saber_1

['created_meta', 'updated_meta']

Algunos registros del DF Saber 11 solo tienen información vacía para las columnas identificadas anteriormente.
Sin embargo, algunos otros registros, contienen muchos más vacíos diferentes de estas dos columnas

In [188]:
filas_nan_saber_1_A = []
filas_nan_saber_1_B = []

# Obtener la serie con el número de fila y cantidad de datos con NaN mayor a 2 según la consulta anterior
res_nans_saber_1_filas = df_saber_1.isna().sum(axis=1)

# Buscar y guardar en una lista el numero del registro que tienen más de 2 registros con Nan
filas_nan_saber_1_A = [res_nans_saber_1_filas .index[i] for i in range(len(res_nans_saber_1_filas)) if res_nans_saber_1_filas [i] > 2]

# Buscar y guardar en una lista el numero del registro que tienen todos sus registros con Nan (86 cantidad de columnas)
filas_nan_saber_1_B = [res_nans_saber_1_filas .index[i] for i in range(len(res_nans_saber_1_filas)) if res_nans_saber_1_filas [i] == 86]

#Cantidad de filas que contienen todos sus registros Nulos
print("Registros con más de 2 columnas con información vacía: ", len(filas_nan_saber_1_A))
print("Registros con todos sus registros con información vacía: ", len(filas_nan_saber_1_B))

Registros con más de 2 columnas con información vacía:  4925
Registros con todos sus registros con información vacía:  0


3.  Las siguientes columnas contienen todos sus datos con NaNs para el DF Saber 11 periodo 1

In [186]:
# SABER 11 PERIODO 2
columnas_nan_saber_2 = []

# Obtener la serie con el nombre de la columna y cantidad de registros con NaN
res_nans_saber_2 = df_saber_2.isna().sum()

# Buscar y guardar en una lista el nombre de las columnas que tienen todos sus registros con Nan
columnas_nan_saber_2 = [res_nans_saber_2.index[i] for i in range(len(res_nans_saber_2)) if res_nans_saber_2[i] == 504872]
columnas_nan_saber_2

['created_meta', 'updated_meta']

Algunos registros del DF Saber 11 periodo 2 solo tienen información vacía para las columnas identificadas anteriormente.
Sin embargo, algunos otros registros, contienen muchos más vacíos diferentes de estas dos columnas

In [264]:
filas_nan_saber_2_A = []
filas_nan_saber_2_B = []

# Obtener la serie con el número de fila y cantidad de datos con NaN mayor a 2 según la consulta anterior
res_nans_saber_2_filas = df_saber_2.isna().sum(axis=1)

# Buscar y guardar en una lista el numero del registro que tienen más de 2 registros con Nan
filas_nan_saber_2_A = [res_nans_saber_2_filas .index[i] for i in range(len(res_nans_saber_2_filas)) if res_nans_saber_2_filas [i] > 2]

# Buscar y guardar en una lista el numero del registro que tienen todos sus registros con Nan (89 cantidad de columnas)
filas_nan_saber_2_B = [res_nans_saber_2_filas .index[i] for i in range(len(res_nans_saber_2_filas)) if res_nans_saber_2_filas [i] == 89]

#Cantidad de filas que contienen todos sus registros Nulos
print("Registros con más de 2 columnas con información vacía: ", len(filas_nan_saber_2_A))
print("Registros con todos sus registros con información vacía: ", len(filas_nan_saber_2_B))

Registros con más de 2 columnas con información vacía:  133046
Registros con todos sus registros con información vacía:  0


### 2. Limpieza de Nans
Se eliminaran todas las columnas que sus registros se encuentran vacíos, de todos los DF analizados

In [265]:
# Data Mintic: de las 23 columnas y según en análisis anterior se deberán eliminar 5 columnas quedando solo 18
df_mintic_v1 = df_mintic.dropna(axis=1, how="all")
df_mintic_v1.shape

(429699, 18)

In [192]:
# Data Saber11 1: de las 86 columnas y según en análisis anterior se deberán eliminar 2 columnas quedando solo 84
df_saber_1_v1 = df_saber_1.dropna(axis=1, how="all")
df_saber_1_v1.shape

(15435, 84)

In [193]:
# Data Saber11 2: de las 89 columnas y según en análisis anterior se deberán eliminar 2 columnas quedando solo 87
df_saber_2_v1 = df_saber_2.dropna(axis=1, how="all")
df_saber_2_v1.shape

(504872, 87)

### 3. Limpieza columnas no informativas

Se deberían eliminar todos los registros de todos los DF que tengan filas totalmente vacías, sin embargo, según en análisis anterior, ninguno de los DF tienen en su totalidad todos los registros de una misma fila en vacíos.

Sin embargo, se analizará la data que contenga información útil para el análisis posterior de cada DF, realizando limpieza de columnas no útiles

In [221]:
# Nombre de las columnas restantes de Mintic
nombre_columnas_mintic_v1 = df_mintic_v1.columns
nombre_columnas_mintic_v1

Index(['sid', 'id', 'position', 'created_at', 'updated_at', 'meta',
       'FECHA_CORTE', 'DEPARTAME_NOMBRE', 'MUNICIPIO_NOMBRE',
       'ESTADO_FORMACION', 'ESTADOS', 'CONVOCATORIA', 'ESTRATO_SOCIAL', 'EDAD',
       'GENERO', 'RUTA', 'GRADO', 'FECHA_VIGENCIA'],
      dtype='object')

In [222]:
# Analizo las columnas y los datos diferentes que tienen para decidir cuáles columnas
# tienen información relevante para el análisis
[df_mintic_v1[col].unique() for col in df_mintic_v1.columns]

[array(['row-sas3_qatz~5pwp', 'row-svx3_76du_vqqc', 'row-xxyq-jzbk_x9ss',
        ..., 'row-4jqb_n4xe.abw2', 'row-pq93-3z4u-h7cz',
        'row-d2ym_v43w~ucct'], dtype=object),
 array(['00000000-0000-0000-C200-BA92F054D3BD',
        '00000000-0000-0000-99AA-2E3888BFFB24',
        '00000000-0000-0000-D72E-7CF7C7526A22', ...,
        '00000000-0000-0000-09BE-4BBD2FE80F6C',
        '00000000-0000-0000-9CD6-6C34B7B4517D',
        '00000000-0000-0000-73B4-52183CA6E2B2'], dtype=object),
 array([0], dtype=int64),
 array([1633555239], dtype=int64),
 array([1633555239], dtype=int64),
 array(['{ }'], dtype=object),
 array(['2021-10-01', '2020-12-31'], dtype=object),
 array(['QUINDIO', 'CAUCA', 'NARIÑO', 'VALLE DEL CAUCA', 'MAGDALENA',
        'CUNDINAMARCA', 'ATLANTICO', 'TOLIMA', 'SANTANDER', 'BOYACA',
        'CALDAS', 'META', 'CORDOBA', 'ANTIOQUIA', 'CESAR', 'RISARALDA',
        'BOLIVAR', 'NORTE DE SANTANDER', 'HUILA', 'BOGOTA', 'SUCRE',
        'CAQUETA', 'VAUPES', 'PUTUMAYO', 'CASANARE', '

Según los resultados obtenidos se dejarán solo las columnas nombradas a continuación para el DF del Mintic:
   'id', 'DEPARTAME_NOMBRE', 'MUNICIPIO_NOMBRE', 'ESTADO_FORMACION', 'ESTADOS' 'ESTRATO_SOCIAL', 'EDAD', 'GENERO', 'RUTA', 'GRADO'
    
Las demás columnas se eliminarán para un dataframe posterior

In [231]:
df_mintic_v2 = df_mintic_v1.drop(columns=['sid', 'position', 'created_at', 'updated_at', 'meta', 'FECHA_CORTE', 'CONVOCATORIA', 'FECHA_VIGENCIA'])
df_mintic_v2.head()

id DEPARTAME_NOMBRE MUNICIPIO_NOMBRE  \
0  00000000-0000-0000-C200-BA92F054D3BD          QUINDIO          ARMENIA   
1  00000000-0000-0000-99AA-2E3888BFFB24          QUINDIO          ARMENIA   
2  00000000-0000-0000-D72E-7CF7C7526A22          QUINDIO          ARMENIA   
3  00000000-0000-0000-50DB-A1B6FA6A2988          QUINDIO          ARMENIA   
4  00000000-0000-0000-6B0A-31FBFCEAA0B3          QUINDIO          ARMENIA   

  ESTADO_FORMACION     ESTADOS ESTRATO_SOCIAL EDAD     GENERO    RUTA GRADO  
0        ASPIRANTE  ASPIRANTES              3   29  MASCULINO  RUTA 2    -1  
1        ASPIRANTE  ASPIRANTES              3   29  MASCULINO  RUTA 2    -1  
2        ASPIRANTE  ASPIRANTES              3   29  MASCULINO  RUTA 2    -1  
3        ASPIRANTE  ASPIRANTES              3   29  MASCULINO  RUTA 2    -1  
4        ASPIRANTE  ASPIRANTES              3   29  MASCULINO  RUTA 2    -1

In [232]:
# Nombre de las columnas restantes de la prueba saber 11 1
nombre_columnas_saber_1_v1 = df_saber_1_v1.columns
nombre_columnas_saber_1_v1

Index(['sid', 'id', 'position', 'created_at', 'updated_at', 'meta',
       'ESTU_TIPODOCUMENTO', 'ESTU_NACIONALIDAD', 'ESTU_GENERO',
       'ESTU_FECHANACIMIENTO', 'PERIODO', 'ESTU_CONSECUTIVO',
       'ESTU_ESTUDIANTE', 'ESTU_PAIS_RESIDE', 'ESTU_TIENEETNIA',
       'ESTU_DEPTO_RESIDE', 'ESTU_COD_RESIDE_DEPTO', 'ESTU_MCPIO_RESIDE',
       'ESTU_COD_RESIDE_MCPIO', 'FAMI_ESTRATOVIVIENDA', 'FAMI_PERSONASHOGAR',
       'FAMI_CUARTOSHOGAR', 'FAMI_EDUCACIONPADRE', 'FAMI_EDUCACIONMADRE',
       'FAMI_TRABAJOLABORPADRE', 'FAMI_TRABAJOLABORMADRE',
       'FAMI_TIENEINTERNET', 'FAMI_TIENESERVICIOTV', 'FAMI_TIENECOMPUTADOR',
       'FAMI_TIENELAVADORA', 'FAMI_TIENEHORNOMICROOGAS', 'FAMI_TIENEAUTOMOVIL',
       'FAMI_TIENEMOTOCICLETA', 'FAMI_TIENECONSOLAVIDEOJUEGOS',
       'FAMI_NUMLIBROS', 'FAMI_COMELECHEDERIVADOS',
       'FAMI_COMECARNEPESCADOHUEVO', 'FAMI_COMECEREALFRUTOSLEGUMBRE',
       'FAMI_SITUACIONECONOMICA', 'ESTU_DEDICACIONLECTURADIARIA',
       'ESTU_DEDICACIONINTERNET', 'ESTU_HORASS

Analizo las columnas y los datos diferentes que tienen para decidir cuáles columnas tienen información relevante para el análisis

In [238]:
[df_saber_1_v1[col].unique() for col in df_saber_1_v1.columns]

[array(['row-k9ci.duxc.nvtz', 'row-rawk~ti8k_t5yx', 'row-mefm-hu4n-mfrb',
        ..., 'row-5gp8-fies~yrr3', 'row-qc8u~cpbw.ka69',
        'row-6e59_xn4a-dps7'], dtype=object),
 array(['00000000-0000-0000-B30A-5F2FE234EE93',
        '00000000-0000-0000-F3E5-3E18272D8C28',
        '00000000-0000-0000-2E67-572B8AFB010B', ...,
        '00000000-0000-0000-E0DC-53D8DB84F7A2',
        '00000000-0000-0000-00FC-440BC52CC658',
        '00000000-0000-0000-0569-078498D91FE7'], dtype=object),
 array([0], dtype=int64),
 array([1615842361], dtype=int64),
 array([1615842361], dtype=int64),
 array(['{ }'], dtype=object),
 array(['CC', 'CE', 'CR', 'NES', 'NIP', 'PC', 'PE', 'PEP', 'RC', 'TI'],
       dtype=object),
 array(['COLOMBIA', 'ESPAÑA', 'ESTADOS UNIDOS', 'HONDURAS',
        'PAÍSES BAJOS - HOLANDA', 'ALEMANIA', 'ARGENTINA', 'BRASIL',
        'CHILE', 'COREA DEL NORTE', 'CUBA', 'ECUADOR', 'EL SALVADOR',
        'FRANCIA', 'GUATEMALA', 'HAITI', 'ITALIA', 'MÉXICO', 'NICARAGUA',
        'PORTUGAL', 

In [240]:
df_saber_1_v2 = df_saber_1_v1.drop(columns=['sid', 'position', 'created_at', 'updated_at', 'meta',
       'ESTU_TIPODOCUMENTO', 'PERIODO', 
       'ESTU_ESTUDIANTE',  'ESTU_TIENEETNIA',
       'FAMI_PERSONASHOGAR','FAMI_CUARTOSHOGAR', 'FAMI_EDUCACIONPADRE', 'FAMI_EDUCACIONMADRE',
       'FAMI_TRABAJOLABORPADRE', 'FAMI_TRABAJOLABORMADRE',
       'FAMI_TIENESERVICIOTV', 'FAMI_TIENELAVADORA', 'FAMI_TIENEHORNOMICROOGAS', 'FAMI_TIENEAUTOMOVIL',
       'FAMI_TIENEMOTOCICLETA', 'FAMI_TIENECONSOLAVIDEOJUEGOS',
       'FAMI_NUMLIBROS', 'FAMI_COMELECHEDERIVADOS',
       'FAMI_COMECARNEPESCADOHUEVO', 'FAMI_COMECEREALFRUTOSLEGUMBRE',
       'ESTU_DEDICACIONLECTURADIARIA',
       'ESTU_HORASSEMANATRABAJA',
       'ESTU_TIPOREMUNERACION', 'COLE_CODIGO_ICFES',
       'COLE_COD_DANE_ESTABLECIMIENTO', 'COLE_NOMBRE_ESTABLECIMIENTO',
       'COLE_GENERO', 'COLE_NATURALEZA', 'COLE_CALENDARIO', 'COLE_BILINGUE',
       'COLE_CARACTER', 'COLE_COD_DANE_SEDE', 'COLE_NOMBRE_SEDE',
       'COLE_SEDE_PRINCIPAL', 'COLE_AREA_UBICACION', 'COLE_JORNADA',
       'COLE_COD_MCPIO_UBICACION', 'COLE_MCPIO_UBICACION',
       'COLE_COD_DEPTO_UBICACION', 'COLE_DEPTO_UBICACION',
       'ESTU_PRIVADO_LIBERTAD', 'ESTU_COD_MCPIO_PRESENTACION',
       'ESTU_MCPIO_PRESENTACION', 'ESTU_DEPTO_PRESENTACION',
       'ESTU_COD_DEPTO_PRESENTACION',
       'ESTU_ESTADOINVESTIGACION', 'ESTU_GENERACION-E'])
df_saber_1_v2.columns

Index(['id', 'ESTU_NACIONALIDAD', 'ESTU_GENERO', 'ESTU_FECHANACIMIENTO',
       'ESTU_CONSECUTIVO', 'ESTU_PAIS_RESIDE', 'ESTU_DEPTO_RESIDE',
       'ESTU_COD_RESIDE_DEPTO', 'ESTU_MCPIO_RESIDE', 'ESTU_COD_RESIDE_MCPIO',
       'FAMI_ESTRATOVIVIENDA', 'FAMI_TIENEINTERNET', 'FAMI_TIENECOMPUTADOR',
       'FAMI_SITUACIONECONOMICA', 'ESTU_DEDICACIONINTERNET',
       'PUNT_LECTURA_CRITICA', 'PERCENTIL_LECTURA_CRITICA',
       'DESEMP_LECTURA_CRITICA', 'PUNT_MATEMATICAS', 'PERCENTIL_MATEMATICAS',
       'DESEMP_MATEMATICAS', 'PUNT_C_NATURALES', 'PERCENTIL_C_NATURALES',
       'DESEMP_C_NATURALES', 'PUNT_SOCIALES_CIUDADANAS',
       'PERCENTIL_SOCIALES_CIUDADANAS', 'DESEMP_SOCIALES_CIUDADANAS',
       'PUNT_INGLES', 'PERCENTIL_INGLES', 'DESEMP_INGLES', 'PUNT_GLOBAL',
       'PERCENTIL_GLOBAL'],
      dtype='object')

In [239]:
# Nombre de las columnas restantes de la prueba saber 11 2
nombre_columnas_saber_2_v1 = df_saber_2_v1.columns
nombre_columnas_saber_2_v1

Index(['sid', 'id', 'position', 'created_at', 'updated_at', 'meta',
       'ESTU_TIPODOCUMENTO', 'ESTU_NACIONALIDAD', 'ESTU_GENERO',
       'ESTU_FECHANACIMIENTO', 'PERIODO', 'ESTU_CONSECUTIVO',
       'ESTU_ESTUDIANTE', 'ESTU_PAIS_RESIDE', 'ESTU_TIENEETNIA',
       'ESTU_DEPTO_RESIDE', 'ESTU_COD_RESIDE_DEPTO', 'ESTU_MCPIO_RESIDE',
       'ESTU_COD_RESIDE_MCPIO', 'FAMI_ESTRATOVIVIENDA', 'FAMI_PERSONASHOGAR',
       'FAMI_CUARTOSHOGAR', 'FAMI_EDUCACIONPADRE', 'FAMI_EDUCACIONMADRE',
       'FAMI_TRABAJOLABORPADRE', 'FAMI_TRABAJOLABORMADRE',
       'FAMI_TIENEINTERNET', 'FAMI_TIENESERVICIOTV', 'FAMI_TIENECOMPUTADOR',
       'FAMI_TIENELAVADORA', 'FAMI_TIENEHORNOMICROOGAS', 'FAMI_TIENEAUTOMOVIL',
       'FAMI_TIENEMOTOCICLETA', 'FAMI_TIENECONSOLAVIDEOJUEGOS',
       'FAMI_NUMLIBROS', 'FAMI_COMELECHEDERIVADOS',
       'FAMI_COMECARNEPESCADOHUEVO', 'FAMI_COMECEREALFRUTOSLEGUMBRE',
       'FAMI_SITUACIONECONOMICA', 'ESTU_DEDICACIONLECTURADIARIA',
       'ESTU_DEDICACIONINTERNET', 'ESTU_HORASS

Analizo las columnas y los datos diferentes que tienen para decidir cuáles columnas tienen información relevante para el análisis.

Adicionalmente solo se dejarán las columnas que también se encuentran en el DF de Saber 11 1


In [237]:
[df_saber_2_v1[col].unique() for col in df_saber_2_v1.columns]

[array(['row-dkkz_ftt3~s52m', 'row-87e6_b245_uisd', 'row-jt88-bz7a_wpg9',
        ..., 'row-k8ve~j4fq.q5u8', 'row-sfht-qyxi_xtbd',
        'row-243r-4wrc.p8hs'], dtype=object),
 array(['00000000-0000-0000-51A2-ED4E60A8A4C5',
        '00000000-0000-0000-776F-6750069D0DFE',
        '00000000-0000-0000-DC23-A86B8ADF5479', ...,
        '00000000-0000-0000-2F10-A90012384309',
        '00000000-0000-0000-03B3-B2EA58E0923E',
        '00000000-0000-0000-2054-CB6AE8FC9320'], dtype=object),
 array([0], dtype=int64),
 array([1615849165], dtype=int64),
 array([1615849165], dtype=int64),
 array(['{ }'], dtype=object),
 array(['TI', 'PEP', 'CE', 'CC', 'NES', 'CR', 'PE', 'PC', 'V', 'NUIP',
        'RC'], dtype=object),
 array(['SUIZA', 'VENEZUELA', 'COLOMBIA', 'ECUADOR', 'GUATEMALA', 'PERÚ',
        'ESTADOS UNIDOS', 'MÉXICO', 'ITALIA', 'COREA DEL SUR', 'URUGUAY',
        'ESTADOS FEDERADOS DE MICRONESIA', 'BOLIVIA', 'PANAMÁ', 'CHILE',
        'REPÚBLICA DOMINICANA', 'EL SALVADOR', 'BRASIL', 'ARGENTI

In [241]:
df_saber_2_v2 = df_saber_2_v1.drop(columns=['sid', 'position', 'created_at', 'updated_at', 'meta',
       'ESTU_TIPODOCUMENTO', 'PERIODO', 'ESTU_ESTUDIANTE', 'ESTU_TIENEETNIA',
       'FAMI_PERSONASHOGAR', 'FAMI_CUARTOSHOGAR', 'FAMI_EDUCACIONPADRE', 'FAMI_EDUCACIONMADRE',
       'FAMI_TRABAJOLABORPADRE', 'FAMI_TRABAJOLABORMADRE',
       'FAMI_TIENESERVICIOTV', 'FAMI_TIENELAVADORA', 'FAMI_TIENEHORNOMICROOGAS', 'FAMI_TIENEAUTOMOVIL',
       'FAMI_TIENEMOTOCICLETA', 'FAMI_TIENECONSOLAVIDEOJUEGOS',
       'FAMI_NUMLIBROS', 'FAMI_COMELECHEDERIVADOS',
       'FAMI_COMECARNEPESCADOHUEVO', 'FAMI_COMECEREALFRUTOSLEGUMBRE',
       'ESTU_DEDICACIONLECTURADIARIA','ESTU_HORASSEMANATRABAJA',
       'ESTU_TIPOREMUNERACION', 'COLE_CODIGO_ICFES',
       'COLE_COD_DANE_ESTABLECIMIENTO', 'COLE_NOMBRE_ESTABLECIMIENTO',
       'COLE_GENERO', 'COLE_NATURALEZA', 'COLE_CALENDARIO', 'COLE_BILINGUE',
       'COLE_CARACTER', 'COLE_COD_DANE_SEDE', 'COLE_NOMBRE_SEDE',
       'COLE_SEDE_PRINCIPAL', 'COLE_AREA_UBICACION', 'COLE_JORNADA',
       'COLE_COD_MCPIO_UBICACION', 'COLE_MCPIO_UBICACION',
       'COLE_COD_DEPTO_UBICACION', 'COLE_DEPTO_UBICACION',
       'ESTU_PRIVADO_LIBERTAD', 'ESTU_COD_MCPIO_PRESENTACION',
       'ESTU_MCPIO_PRESENTACION', 'ESTU_DEPTO_PRESENTACION',
       'ESTU_COD_DEPTO_PRESENTACION', 'ESTU_INSE_INDIVIDUAL', 'ESTU_NSE_INDIVIDUAL',
       'ESTU_NSE_ESTABLECIMIENTO', 'ESTU_ESTADOINVESTIGACION',
       'ESTU_GENERACION-E'])
df_saber_2_v2.columns

Index(['id', 'ESTU_NACIONALIDAD', 'ESTU_GENERO', 'ESTU_FECHANACIMIENTO',
       'ESTU_CONSECUTIVO', 'ESTU_PAIS_RESIDE', 'ESTU_DEPTO_RESIDE',
       'ESTU_COD_RESIDE_DEPTO', 'ESTU_MCPIO_RESIDE', 'ESTU_COD_RESIDE_MCPIO',
       'FAMI_ESTRATOVIVIENDA', 'FAMI_TIENEINTERNET', 'FAMI_TIENECOMPUTADOR',
       'FAMI_SITUACIONECONOMICA', 'ESTU_DEDICACIONINTERNET',
       'PUNT_LECTURA_CRITICA', 'PERCENTIL_LECTURA_CRITICA',
       'DESEMP_LECTURA_CRITICA', 'PUNT_MATEMATICAS', 'PERCENTIL_MATEMATICAS',
       'DESEMP_MATEMATICAS', 'PUNT_C_NATURALES', 'PERCENTIL_C_NATURALES',
       'DESEMP_C_NATURALES', 'PUNT_SOCIALES_CIUDADANAS',
       'PERCENTIL_SOCIALES_CIUDADANAS', 'DESEMP_SOCIALES_CIUDADANAS',
       'PUNT_INGLES', 'PERCENTIL_INGLES', 'DESEMP_INGLES', 'PUNT_GLOBAL',
       'PERCENTIL_GLOBAL'],
      dtype='object')